export const Constants = {
  SUCCESS: "ALERT_SUCCESS",
  ERROR: "ALERT_ERROR",
  CLEAR: "ALERT_CLEAR",
  SHOW_LOADING: "SHOW_LOADING",
  CLOSE_LOADING: "CLOSE_LOADING",
  CLOSE_NOTIFICATION: "CLOSE_NOTIFICATION",
  FETCH_POSTS: "FETCH_POSTS",
  RESULT: "RESULT",
};
